import type { CmsCatalogService } from "@/lib/cms";

/**
 * Shown when the CMS returns no catalog services (empty DB or API failure).
 * Once the admin adds services via the CMS, these are replaced automatically.
 * Source of truth for initial data — mirrors what migrate.js seeds into the DB.
 */
export const FALLBACK_CATALOG_SERVICES: CmsCatalogService[] = [
  {
    slug:        "checkweighers",
    title:       "Checkweighers",
    description: "Dynamic checkweighers verify every product on your line against target weight tolerances, instantly rejecting underweight or overweight items without slowing throughput.",
    badge:       "High Speed",
    image_url:   "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&q=80",
    specs:       "Up to 300 packs/min|±0.1g accuracy|IP65 rated|Auto-reject",
    sort_order:  10,
  },
  {
    slug:        "bagging-powder-filling",
    title:       "Bagging & Powder Filling",
    description: "Combine precision weighing with automated packaging to deliver consistent fill weights at high throughput — reducing product giveaway and operator dependency.",
    badge:       "Automation",
    image_url:   "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    specs:       "100g–50kg fill range|1,200 bags/hr|±0.5% accuracy|SS304/316",
    sort_order:  20,
  },
  {
    slug:        "platform-tabletop-scales",
    title:       "Platform & Tabletop Scales",
    description: "From compact bench scales to heavy-duty floor platforms, our Legal Metrology approved scales deliver consistent accuracy across all industrial and laboratory environments.",
    badge:       "Certified",
    image_url:   "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    specs:       "1kg–3,000kg|0.1g readability|IP54/IP65|RS232/USB",
    sort_order:  30,
  },
  {
    slug:        "tank-weighing",
    title:       "Tank Weighing Systems",
    description: "Compression and tension load cell arrays provide continuous, accurate weight data for process tanks — enabling live inventory control and automated batch management.",
    badge:       "Process Control",
    image_url:   "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
    specs:       "Compression & tension|ATEX rated options|PLC integration|Live inventory",
    sort_order:  40,
  },
  {
    slug:        "hopper-weighing",
    title:       "Hopper Weighing",
    description: "Hopper weighing systems deliver accurate dosing and batching with full PLC integration — eliminating manual measurement and enabling fully automated production workflows.",
    badge:       "Batching",
    image_url:   "https://images.unsplash.com/photo-1565043589221-1a6fd9ae45c7?w=800&q=80",
    specs:       "Automated dosing|PLC integration|SS construction|Multi-hopper",
    sort_order:  50,
  },
  {
    slug:        "vessel-weighing",
    title:       "Vessel Weighing",
    description: "Precision load cell mounting kits for new or retrofit installation on process vessels, with hygienic designs for pharma and food applications and full process control integration.",
    badge:       "Pharma Ready",
    image_url:   "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&q=80",
    specs:       "Retrofit-friendly|Hygienic design|ATEX options|Continuous monitoring",
    sort_order:  60,
  },
  {
    slug:        "drum-tin-filling",
    title:       "Drum & Tin Filling Systems",
    description: "Semi-automatic and fully automatic drum filling systems combine precision weighing with fill control — ensuring every container meets exact specification with operator safety features.",
    badge:       "Automated",
    image_url:   "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
    specs:       "1L–1,000L range|±0.1% accuracy|Manual/semi/full auto|SS304/316",
    sort_order:  70,
  },
  {
    slug:        "crane-scales",
    title:       "Crane Scales (Coil Weighing)",
    description: "Wireless crane scales deliver accurate weight readings for steel coils, heavy fabrications, and overhead crane operations without interrupting lifting workflows.",
    badge:       "Heavy Duty",
    image_url:   "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    specs:       "500kg–100T|±0.1% accuracy|Wireless display|IP65 · Battery",
    sort_order:  80,
  },
  {
    slug:        "retail-scales",
    title:       "Retail Scales (Gold, Silver & Lab)",
    description: "NABL-traceable retail scales for gold, silver, and pharmaceutical counters — with tamper-proof design, dual LCD display, and Legal Metrology certification for trade use.",
    badge:       "Legal Metrology",
    image_url:   "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    specs:       "50g–30kg|0.001g readability|Dual LCD|NABL traceable",
    sort_order:  90,
  },
  {
    slug:        "export-weighing",
    title:       "Export Weighing Solutions",
    description: "Export-grade weighbridges and container scales certified for international customs compliance — with multi-currency display, documentation integration, and international calibration certificates.",
    badge:       "OIML Certified",
    image_url:   "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80",
    specs:       "OIML certified|Customs docs|Multi-currency|International certs",
    sort_order:  100,
  },
  {
    slug:        "standard-weight-boxes",
    title:       "Standard Weight Boxes",
    description: "Complete sets and individual weights in cast iron, stainless steel, and precision classes — supplied with NABL-traceable calibration certificates for legal and industrial use.",
    badge:       "NABL Traceable",
    image_url:   "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    specs:       "Classes E1–M3|Cast iron & SS|1mg–5,000kg|NABL certificates",
    sort_order:  110,
  },
  {
    slug:        "hardness-testing",
    title:       "Hardness Testing Devices",
    description: "Multi-scale hardness testing instruments for pharmaceutical tablet quality control and industrial material testing — with digital readout, GMP-compatible design, and calibration support.",
    badge:       "GMP Compatible",
    image_url:   "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80",
    specs:       "Rockwell/Brinell/Vickers|Digital readout|GMP compatible|Calibration support",
    sort_order:  120,
  },
  {
    slug:        "weighing-api",
    title:       "Weighing API Services",
    description: "Bridge physical weighing devices with your digital infrastructure — real-time data sync, webhook support, and secure API endpoints for ERP, LIMS, WMS, and custom software integration.",
    badge:       "Integration",
    image_url:   "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&q=80",
    specs:       "REST API|Real-time sync|ERP/LIMS/WMS|Webhook support",
    sort_order:  130,
  },
];
